version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello_laravel_app
    ports:
      - "8000:8000" # host:container
    volumes:
      - ./:/var/www/html # mount project
    environment:
      - TZ=UTC
    command: php artisan serve --host=0.0.0.0 --port=8000
