apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_NAME: Laravel
  APP_ENV: production
  APP_DEBUG: "false"
  DB_CONNECTION: sqlite
  DB_DATABASE: /var/www/html/database/database.sqlite
