apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      volumes:
        - name: app-key
          emptyDir: {}
      initContainers:
        - name: generate-app-key
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              php artisan key:generate --show > /app-key/APP_KEY
          volumeMounts:
            - name: app-key
              mountPath: /app-key
      containers:
        - name: laravel-app
          image: fmahmud26/laravel-app:${IMAGE_TAG}
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-key-config
                  key: APP_KEY
          volumeMounts:
            - name: app-key
              mountPath: /app-key
