apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
type: Opaque
data:
  # Base64 encode your Laravel APP_KEY, e.g. php artisan key:generate --show
  APP_KEY: gxHu1rn6P0fRu3mdMmJ8O0y1NMvrDf7rkX/O36qgMLg=
