apiVersion: v1
kind: Service
metadata:
  name: laravel-app
spec:
  type: LoadBalancer
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80         # ELB listens on 80
      targetPort: 80   # Container listens on 80
