apiVersion: v1
kind: Service
metadata:
  name: laravel-app
spec:
  type: LoadBalancer
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80        # Public LB port
      targetPort: 80  # Container port
